services:
  - type: web
    name: ai-virtual-doctor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-doctor-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: ai-doctor-db
    plan: free
    databaseName: ai_doctor
